import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { LayoutProps } from "@/types/layout.types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS Fullstack Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<LayoutProps>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <ThemeToggle /> */}
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
